import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Networks from "./header";
import Footer from "./footer";
import Section1 from "./section1";
import Section2 from "./section2";
import Section3 from "./section3";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Networks />
      <Section1 />
      <Section2 />
      <Section3 />
      <Footer />
    </div>
  );
}
